export enum FacturaStatusEnum {
  PENDIENTE = 'PENDIENTE',
  ENVIADA = 'ENVIADA',
  REVERTIDA = 'REVERTIDA',
  RECHAZADA = 'RECHAZADA',
  OBSERVADA = 'OBSERVADA',
  ANULADA = 'ANULADA',
  VALIDADA = 'VALIDADA',
}
